version: '3'

services:
  nginx:
    container_name: ${DOCKER_PROJECT_NAME}_nginx
    image: nginx:1.19
    restart: unless-stopped
    volumes:
      - ./docker/nginx/logs:/var/log/nginx
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    ports:
      - ${DOCKER_NGINX_PORT}:80

  
